const Themes = {
    'default': 'default',
    '3024-day': '3024-day',
    '3024-night': '3024-night',
    'abcdef': 'abcdef',
    'ambiance-mobile': 'ambiance-mobile',
    'ambiance': 'ambiance',
    'base16-dark': 'base16-dark',
    'base16-light': 'base16-light',
    'bespin': 'bespin',
    'blackboard': 'blackboard',
    'cobalt': 'cobalt',
    'colorforth': 'colorforth',
    'dracula': 'dracula',
    'duotone-dark': 'duotone-dark',
    'duotone-light': 'duotone-light',
    'eclipse': 'eclipse',
    'elegant': 'elegant',
    'erlang-dark': 'erlang-dark',
    'hopscotch': 'hopscotch',
    'icecoder': 'icecoder',
    'isotope': 'isotope',
    'lesser-dark': 'lesser-dark',
    'liquibyte': 'liquibyte',
    'material': 'material',
    'mbo': 'mbo',
    'mdn-like': 'mdn-like',
    'midnight': 'midnight',
    'monokai': 'monokai',
    'neat': 'neat',
    'neo': 'neo',
    'night': 'night',
    'oceanic-next': 'oceanic-next',
    'panda-syntax': 'panda-syntax',
    'paraiso-dark': 'paraiso-dark',
    'paraiso-light': 'paraiso-light',
    'pastel-on-dark': 'pastel-on-dark',
    'railscasts': 'railscasts',
    'rubyblue': 'rubyblue',
    'seti': 'seti',
    'shadowfox': 'shadowfox',
    'solarized': 'solarized',
    'the-matrix': 'the-matrix',
    'tomorrow-night-bright': 'tomorrow-night-bright',
    'tomorrow-night-eighties': 'tomorrow-night-eighties',
    'ttcn': 'ttcn',
    'twilight': 'twilight',
    'vibrant-ink': 'vibrant-ink',
    'xq-dark': 'xq-dark',
    'xq-light': 'xq-light',
    'yeti': 'yeti',
    'zenburn': 'zenburn',
};

/* const OldThemes = {
    ambiance: 'Ambiance',
    chaos: 'Chaos',
    chrome: 'Chrome',
    clouds: 'Clouds',
    clouds_midnight: 'Clouds Midnight',
    cobalt: 'Cobalt',
    crimson_editor: 'Crimson Editor',
    dawn: 'Dawn',
    dreamweaver: 'Dreamweaver',
    eclipse: 'Eclipse',
    github: 'Github',
    idle_fingers: 'Idle Fingers',
    iplastic: 'Iplastic',
    katzenmilch: 'Katzenmilch',
    kr_theme: 'Kr Theme',
    kuroir: 'Kuroir',
    merbivore: 'Merbivore',
    merbivore_soft: 'Merbivore Soft',
    mono_industrial: 'Mono Industrial',
    monokai: 'Monokai',
    pastel_on_dark: 'Pastel on Dark',
    solarized_dark: 'Solarized Dark',
    solarized_light: 'Solarized Light',
    sqlserver: 'SQLServer',
    terminal: 'Terminal',
    textmate: 'Textmate',
    tomorrow: 'Tomorrow',
    tomorrow_night: 'Tomorrow Night',
    tomorrow_night_blue: 'Tomorrow Night Blue',
    tomorrow_night_bright: 'Tomorrow Night Bright',
    tomorrow_night_eighties: 'Tomorrow Night Eighties',
    twilight: 'Twilight',
    vibrant_ink: 'Vibrant Ink',
    xcode: 'xCode'
}; */

module.exports = {
    all: Themes,
    require: () => {
        Object.keys(Themes).forEach((themeKey) => {
            if(themeKey !== 'default')
                require('codemirror/theme/' + themeKey + '.css')
        });
    }
};
