version: '3'
services:
  app_prod:
    build:
      context: .
      args:
        - app_env=production
    image: 'realtime-editor'
    environment:
      - SERVER_PORT=3003
      - MONGO_DB_URI=mongodb://admin:password123@mongodb/realtime-editor
      - MONGO_SESSION_COLLECTION=sessions
      - SESSION_SECRET=
      - DEBUG=editor:*
      - BASE_URL=http://locahost:3003
      - CTU_CLIENT_ID=
      - CTU_CLIENT_SECRET=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - FACEBOOK_APP_ID=
      - FACEBOOK_APP_SECRET=
      - TWITTER_CONSUMER_KEY=
      - TWITTER_CONSUMER_SECRET=
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_SECURE=
      - SMTP_USER=
      - SMTP_PASSWORD=
    ports:
      - "3003:3003"
    networks:
      - app-tier
    depends_on:
      - "mongodb"

  app_dev:
    build:
      context: .
      args:
        - app_env=development
    volumes:
      - ./app/package.json:/app/package.json
      - ./app/yarn.lock:/app/yarn.lock
      - ./app/bin:/app/bin
      - ./app/src:/app/src
      - ./app/client/package.json:/app/client/package.json
      - ./app/client/yarn.lock:/app/client/yarn.lock
      - ./app/client/public:/app/client/public
      - ./app/client/src:/app/client/src
      - ./app/client/build-prod:/app/client/build-prod
      - ./app/.env:/app/.env
    environment:
      - SERVER_PORT=3001
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - app-tier
    depends_on:
      - "mongodb"

  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/bitnami
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=realtime-editor
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
